export const linkItems = [
  { name: "Deals" },
  { name: "What's New" },
  { name: "Delivery" },
];

export const categoryOptions = [
  { name: "Clothes", description: "Stylish and Fashionable" },
  { name: "Tech", description: "Entertainment and fun" },
  {
    name: "Furniture",
    description: "Luxurious furniture",
  },
  { name: "Books", description: "Wide collection" },
  { name: "Sneakers", description: "Recognized brands." },
  { name: "Hand Bags", description: "Stylish hand bags" },
];
export const locationOptions = [
  { name: "Location" },
  { name: "Nairobi" },
  { name: "Mombasa" },
  { name: "Kisumu" },
  { name: "Naivasha" },
  { name: "Naivasha" },
  { name: "Nyeri" },
  { name: "Thika" },
  { name: "Eldoret" },
  { name: "Isiolo" },
];

export const products = [
  {
    id: 0,
    name: "AirPodMax",
    details: "Amazing sound and bass",
    rating: 4,
    price: 599,
    colors: ["red", "gray", "blue", "black"],
    stock: 12,
    count: 1,
    category: "Tech",
    deal: "10% off",
    tags: ["AirPodMax", "headphones", "Apple", "Music", "Tech"],
    general: {
      Brand: "apple",
      Model: "Tx-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Airpod Max",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 1,
    name: "ExB Headphones",
    details: "Awesome ExB Headphones.",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Tech",
    deal: "10% off",
    newDeal: true,
    tags: ["ExB", "headphones", "Samsung", "Music", "Tech"],
    general: {
      Brand: "apple",
      Model: "Tx-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Airpod Max",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 2,
    name: "MacBook",
    details: "MacBook Pro",
    rating: 4,
    price: 599,
    colors: ["red", "gray", "blue", "black"],
    stock: 12,
    count: 1,
    category: "Tech",
    deal: "30% off",
    tags: ["MacBook", "laptop", "Apple", "Tech"],
    general: {
      Brand: "apple",
      Model: "Tx-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Airpod Max",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 3,
    name: "Television",
    details: "TCL Television",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Tech",
    tags: ["TCL", "television", "electronic", "digital", "Tech"],
    general: {
      Brand: "apple",
      Model: "Tx-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Airpod Max",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 4,
    name: "Subwoofer",
    details: "The best sound",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Tech",
    newDeal: true,
    tags: ["subwoofer", "sony", "bluetooth", "Music", "Tech"],
    general: {
      Brand: "apple",
      Model: "Tx-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Airpod Max",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 5,
    name: "Table",
    details: "Acacia Table",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Furniture",
    deal: "25% off",
    newDeal: true,
    tags: ["Femer", "Furniture", "Table", "acacia"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 6,
    name: "Office Chair",
    details: "Office Chair",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Furniture",
    newDeal: true,
    tags: ["wooden", "Furniture", "chair", "office"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 7,
    name: "Bed",
    details: "King Size Bed",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Furniture",
    newDeal: true,
    tags: ["king", "Furniture", "bed", "wooden"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 8,
    name: "Plastic Chair",
    details: "Plastic Chair",
    newDeal: true,
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Furniture",
    tags: ["chair", "Furniture", "plastic"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 9,
    name: "Cabinet",
    details: "Home cabinet",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    newDeal: true,
    category: "Furniture",
    tags: ["Femer", "Furniture", "Cabinet", "wooden"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 10,
    name: "Money",
    details: "Get Rich.",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Books",
    tags: ["books", "money", "rich"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 11,
    name: "Psychology",
    details: "Learn Psychology",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Books",
    tags: ["books", "psychology"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 12,
    name: "Science",
    details: "The origin",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Books",
    tags: ["books", "science", "universe"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 13,
    name: "Be Fit",
    details: "Fitness",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Books",
    tags: ["books", "Fitness"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 14,
    name: "Geology",
    details: "Geology",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Books",
    tags: ["books", "geology", "earth"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 15,
    name: "Leather Jacket",
    details: "For men",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Clothes",
    deal: "15% off",
    tags: ["men", "jacket", "leather", "style"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 16,
    name: "Men's Shirt",
    details: "T-shirt for men",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Clothes",
    tags: ["men", "T-Shirt", "shirt"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 17,
    name: "Dress",
    details: "Dinner dress",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Clothes",
    tags: ["women", "dress", "ladies", "dinner"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 18,
    name: "Socks",
    details: "men's socks",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Clothes",
    tags: ["men", "socks", "cotton"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 19,
    name: "Shorts",
    details: "Men shorts",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Clothes",
    tags: ["men", "socks", "cotton"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 20,
    name: "Nike",
    details: "Nike sneakers",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Sneakers",
    deal: "10% off",
    tags: ["Nike", "sneakers", "Style"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 21,
    name: "Puma",
    details: "Puma sneakers",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Sneakers",
    tags: ["Puma", "sneakers", "Style"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 22,
    name: "Nike special",
    details: "Nike special sneakers",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Sneakers",
    tags: ["Nike", "sneakers", "Style"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 23,
    name: "Puma special",
    details: "Puma special sneakers",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Sneakers",
    deal: "20% off",
    tags: ["Puma", "sneakers", "Style"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 24,
    name: "Nike 12",
    details: "Table From Femer.co",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Sneakers",
    tags: ["Nike", "sneakers", "Style"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 25,
    name: "Leather Hand Bag",
    details: "Leather hand bag",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Hand Bags",
    deal: "15% off",
    tags: ["Hand bag", "ladies", "women"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 26,
    name: "Perl Hand bag",
    details: "Pearl hand bag",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Hand Bags",
    tags: ["Hand bag", "ladies", "women"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 27,
    name: "Classic Hand bag",
    details: "Classic Hand Bag",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Hand Bags",
    deal: "15% off",
    tags: ["Hand bag", "ladies", "women"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 28,
    name: "Queens Hand Bag",
    details: "queens hand bag",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    category: "Hand Bags",
    deal: "10% off",
    tags: ["Hand bag", "ladies", "women"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
  {
    id: 29,
    name: "Rose Handbag",
    details: "Rose Hand bag",
    rating: 4,
    price: 345,
    colors: ["red", "gray", "blue", "black"],
    stock: 20,
    count: 1,
    deal: "10% off",
    category: "Hand Bags",
    tags: ["Hand bag", "ladies", "women"],
    general: {
      Brand: "Femer",
      Model: "Fz-1vs",
      Price: "$599.0",
      Release: "April 2020",
      MOdelNumber: "Femr-ss2",
      Connectivity: "wireless",
    },
    ProductDetails: {
      Microphone: "yes",
      DriverType: "dynamic",
      NoOfDrivers: "1",
      WaterResist: "no",
      Weight: "365g",
      BateryLife: "20hrs",
    },
  },
];
